### ISSUE TITLE
Mars-Java的瘦身计划

### ISSUE THREAD

**Issue by yuyenews** [yuyenews/Martian#156]
Mars-Java 从出身的那天起，就是基于一个理念的：它要小，越小越好，他要简单，越容易用越好。

为了达到这个理念，我们一直在坚持几件事：

1. 绝不玩花哨的东西，大家会什么，我们就做什么，而不是制定新规则给大家用。
2. 尽可能的去提取市面上的精华，去掉不要的东西。

**第一点很好理解，也是没少被吐槽的地方，那就是第一眼看上去没什么新意，这其实很好解释：**

因为无论怎么变，都是用Java写的嘛，本质上一点区别都没。那既然大家已经习惯了用筷子吃饭，我为什么要去推刀叉给大家呢？大家的最终目的无非就是用工具做出一个符合需求的项目嘛，没必要给使用者添加学习成本。

**与其把重点放在发明刀叉上，不如把筷子的质量提高一些，让使用者能够更好地用餐。所以，我们坚持 尽量不玩花哨的东西，不制造新玩法。如果有人感兴趣，拿起来就可以直接用，完全不需要花大量时间学习。**

-----------------------------------------

第二点也很好理解，这个项目做到现在为止已经有一年多了，我们提取了最常用的ioc，aop，mvc，数据库操作，并自己做了实现。同时只保留了bean的单例，去掉了不常用scope。

现在，又去掉了第三方容器，完全基于JRE类库开发了一个Http服务，这个服务只保留了最常用的几个地方：

- 传参：支持raw，formdata，表单提交
- 图片上传：支持一次性传多个
- 图片下载
- Json响应：后端给前端返回Json数据

接下来的发展方向是一步步的 去掉第三方依赖，并挑选这些依赖中最常用的特性，自己实现。

-----------------------------------------

尽管看起来没有新意，尽管缺乏大量的实战历练使人们不敢相信它，但我会坚持下去，总有一天，我可以打造一套自己的全家桶

将瘦身进行到底！。

**Comment by holicc** [comment]
考虑使用Graalvm编译成native的吗？ 这样可以更小
